### ISSUE TITLE
Create 'add-my-friend-profile' feature #4

### ISSUE THREAD

**Issue by LiquifiedPopuko** [LiquifiedPopuko/supreme-meme#8]
- Create `feature-add-my-friend-profile` branch from `development` branch.
- Create link to `friend_profile.html` in `index.html`
- Create `feature-friend-image` branch from `development` branch
- Put friend's image in `index.html`
- Commit

**Comment by thanaponglaboratory** [comment]
add profile and pic 
884f349c8e30730b3962fdd1b1c830a763112458
25d46ca6909b2e57ce5152eb955bb3c053833c92
